language: node_js
env:
  - CXX=g++-4.8
node_js:
  - v6
  - v4
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtesseract-dev libleptonica-dev tesseract-ocr-eng
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
